server:
  port: 8082 #指定启动端口号
  servlet:
    context-path: /boot

spring:
  application:
    name: test-service
  profiles:
    active: dev  #默认环境（开发环境）

  datasource:
    primary:
      type: com.alibaba.druid.pool.DruidDataSource   #这里是配置druid连接池，以下都是druid的配置信息
      jdbc-url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
      driver-class-name: com.mysql.cj.jdbc.Driver #报红忽略，是被问题，时可用的
      username: root
      password: 123456
      maxActive: 40 #数据库连接池得最大值，同一时间能从池中分配得最大数量，0时表示无限制
      initialSize: 1 #连接初始值，连接池启动时创建的连接数量的初始值
      maxWait: 60000
      minIdle: 1 #最小空闲值.当空闲的连接数少于阀值时，连接池就会预申请去一些连接，以免洪峰来时来不及申请
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x' #验证数据库连接查询语句的有效性,此处时mysql得配置，Oracle:select 1 from dual
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true  #是否对已备语句进行池管理（布尔值），是否对PreparedStatement进行缓存
      maxOpenPreparedStatements: 20
    secondary:
      type: com.alibaba.druid.pool.DruidDataSource   #这里是配置druid连接池，以下都是druid的配置信息
      jdbc-url: jdbc:mysql://localhost:3306/two?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
      driver-class-name: com.mysql.cj.jdbc.Driver #报红忽略，识别问题，时可用的
      username: root
      password: 123456
      maxActive: 40 #数据库连接池得最大值，同一时间能从池中分配得最大数量，0时表示无限制
      initialSize: 1 #连接初始值，连接池启动时创建的连接数量的初始值
      maxWait: 60000
      minIdle: 1 #最小空闲值.当空闲的连接数少于阀值时，连接池就会预申请去一些连接，以免洪峰来时来不及申请
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x' #验证数据库连接查询语句的有效性,此处时mysql得配置，Oracle:select 1 from dual
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true  #是否对已备语句进行池管理（布尔值），是否对PreparedStatement进行缓存
      maxOpenPreparedStatements: 20

  devtools:
    enabled: true #热部署配置

  mvc:
    view:
      prefix: /  #默认是src/main/webapp 所以在这里就没配置了
      suffix: .jsp

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss  #日期格式化
    serialization:
      indent_output: true  #格式化输出
      fail_on_empty_beans: false  #忽略无法转换的对象

    defaultPropertyInclusion: NON_EMPTY  #设置空如何序列化
    deserialization:
      fail_on_unknown_properties: false  #允许对象忽略json中不存在的属性
    parser:
      allow_unquoted_control_chars: true  #允许出现特殊字符和转义符
      allow_single_quotes: true  #允许出现单引号

  logging:
    level: debug #日志配置
    path: F:/boot-log
    file: mylog.log

  redis:
    database: 0
    host: localhost
    port: 6379
    password:
    timeout: 10000 #连接超时时间 1秒
    jedis:
      pool:
        max-active: 8 #连接池最大连接数 使用负值表示没有限制
        max-wait: -1 #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8 #连接池中的最大空闲连接
        min-idle: 0 #连接池中的最小空闲连接

  rabbitmq:
    virtual-host: /
    host: localhost
    port: 5672
    username: zxf
    password: 5632637
    listener:
      concurrency: 10
      max-concurrency: 20
      prefetch: 50




mybatis:






